In [1]:
import numpy as np

In [2]:
#zeros , #ones , #eye , #diag randint , rand , randn

In [3]:
arr = np.zeros ( ( 2,3 ) )
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
arr = np.ones ( ( 2,3 ) )
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
arr = np.eye ( 3,4 )
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [6]:
arr = np.eye ( 4 )
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
arr = np.diag ( [ 1,2,3,4 ] )
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [8]:
rand_arr = np.random.randint ( 1,15,4 ) # it gives any 4 ints from 1 to 15 excluding 15 only 
rand_arr

array([5, 3, 2, 6])

In [9]:
rand_arr = np.random.rand ( 4 ) #  simply gives 4  elements between 0 and 1
rand_arr

array([0.28639654, 0.5067737 , 0.97184949, 0.13863705])

In [10]:
rand_arr = np.random.rand (2,3) # gives a 2D array whose elements are between 0 and 1
rand_arr

array([[0.89073036, 0.37760447, 0.67946869],
       [0.2380277 , 0.54392647, 0.71163886]])

In [11]:
rand_arr = np.random.randn ( 15000 ) # returns 15000 numbers in rand_arr whose standard normal distribution is neary equal to 0
np.mean ( rand_arr )

0.006059689688384422