In [1]:
import numpy as np

In [2]:
arr = np.random.randint ( 1,100,50 ) # creating 1D array inputing 50 random integers from 1 to 99
arr

array([17, 28, 43, 38, 54, 50,  7, 66, 96, 96, 43, 51, 83, 61, 90, 43, 49,
       37, 47,  4, 78, 14, 85, 76, 84, 73, 40, 14, 85, 80, 26, 68, 46, 21,
       34, 30, 90, 87, 93, 72, 16, 51, 93, 97, 80, 41, 89, 10, 48, 45])

In [3]:
arr = arr.reshape (5,10) # reshaping arr in 2D array (5,10)
arr

array([[17, 28, 43, 38, 54, 50,  7, 66, 96, 96],
       [43, 51, 83, 61, 90, 43, 49, 37, 47,  4],
       [78, 14, 85, 76, 84, 73, 40, 14, 85, 80],
       [26, 68, 46, 21, 34, 30, 90, 87, 93, 72],
       [16, 51, 93, 97, 80, 41, 89, 10, 48, 45]])

In [4]:
arr = arr.reshape (2,-1) # now computer will automatically fit a number for -1  
arr # if possible mutiples then it will show an error 

array([[17, 28, 43, 38, 54, 50,  7, 66, 96, 96, 43, 51, 83, 61, 90, 43,
        49, 37, 47,  4, 78, 14, 85, 76, 84],
       [73, 40, 14, 85, 80, 26, 68, 46, 21, 34, 30, 90, 87, 93, 72, 16,
        51, 93, 97, 80, 41, 89, 10, 48, 45]])