In [1]:
import numpy as np

In [3]:
np.random.seed(12)
arr = np.random.randint(1,101,10)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [6]:
arr.size

10

In [8]:
arr[0]

76

In [11]:
arr[0:6:2]

array([76,  7,  4])

In [13]:
matrix = np.random.randint(1,100,25).reshape(5,5)
matrix

array([[74, 46, 31, 33, 28],
       [60, 90, 60, 89, 80],
       [26, 98, 57,  5, 97],
       [69, 66, 45, 38, 76],
       [69, 54, 76, 54, 48]])

In [14]:
matrix[0,0]

74

In [15]:
matrix[1:4 ,1:4]

array([[90, 60, 89],
       [98, 57,  5],
       [66, 45, 38]])