In [9]:
import numpy as nb

In [10]:
arr = nb.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
mask = arr > 5
arr [ mask ]

array([ 6,  7,  8,  9, 10])

In [12]:
arr [ arr < 4 ]

array([1, 2, 3])

In [13]:
arr [ arr % 2 == 0 ]

array([ 2,  4,  6,  8, 10])

In [14]:
arr [ arr == 5 ]

array([5])