In [8]:
import numpy as np

In [9]:
arr = np.array ( [ 1,2,3,4 ] ) . reshape ( 2,2 )
arr* 2

array([[2, 4],
       [6, 8]])

In [10]:
arr

array([[1, 2],
       [3, 4]])

In [11]:
arr + 5

array([[6, 7],
       [8, 9]])

In [12]:
arr** 4

array([[  1,  16],
       [ 81, 256]], dtype=int32)

In [14]:
arr/0

C:\Users\shiv\AppData\Local\Temp\ipykernel_1080\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([[inf, inf],
       [inf, inf]])

In [15]:
1/0

ZeroDivisionError: division by zero