In [1]:
import numpy as np
arr1 = np.array ( [ 1,2,3,4 ] )
arr2 = np.array ( [ 5,6,7,8 ] )
arr1+ arr2

array([ 6,  8, 10, 12])

In [2]:
arr1*arr2 # other mathematical operations can also be done

array([ 5, 12, 21, 32])

In [4]:
np.random.seed ( 123 )
matrix1 = np.random.randint ( 1,12,9 ) .reshape ( 3,3 )
matrix2 = np.random.randint ( 5,15,9 ) .reshape ( 3,3 )
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [5]:
matrix2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [6]:
matrix1 * matrix2

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [7]:
matrix1.dot(matrix2)

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])