In [3]:
import numpy as np
np.random.seed(123)
matrix = np.random.randint(1,15,9).reshape(3,3)
matrix

array([[14,  3, 13],
       [ 3,  7,  2],
       [ 4, 11, 12]])

In [6]:
np.min(matrix)
np.max(matrix)

14

In [7]:
np.min(matrix, axis=1) # to find min of all the rows here since axis is 1

array([3, 2, 4])

In [9]:
np.max(matrix, axis=0) # to find max of all the columns here since axis is 0

array([14, 11, 13])

In [12]:
np.sum(matrix)
np.cumsum(matrix)

array([14, 17, 30, 33, 40, 42, 46, 57, 69])

In [13]:
np.cumsum(matrix, axis=1)

array([[14, 17, 30],
       [ 3, 10, 12],
       [ 4, 15, 27]])

In [15]:
np.cumsum(matrix, axis=0)

array([[14,  3, 13],
       [17, 10, 15],
       [21, 21, 27]])

In [18]:
np.product(matrix)
np.product(matrix, axis=1)
# np.product(matrix, axis=0)


array([546,  42, 528])