### Import numpy library  

In [8]:
import numpy as np

### Create an Array using array function  

In [9]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

### Create an Array containing numbers from 20 to 40 

In [10]:
arr2 = np.arange(20,41)
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

### Create an array which contain 10 elements and every element is 5  

In [11]:
fives = np.ones(10)*5
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### create a 1-d array and then convert it into 3-d array  

In [12]:
arr3 = np.random.randint(1,50,24).reshape(3,4,2)
arr3

array([[[39, 34],
        [22, 31],
        [28, 35],
        [34, 13]],

       [[41,  4],
        [43,  6],
        [ 1, 12],
        [35, 11]],

       [[23, 14],
        [19, 37],
        [16, 44],
        [28, 45]]])

### Create 2-d array which contains random 25 numbers between 0 and 1 

In [13]:
arr4 = np.random.rand(4,5)
arr4

array([[0.94416002, 0.50183668, 0.62395295, 0.1156184 , 0.31728548],
       [0.41482621, 0.86630916, 0.25045537, 0.48303426, 0.98555979],
       [0.51948512, 0.61289453, 0.12062867, 0.8263408 , 0.60306013],
       [0.54506801, 0.34276383, 0.30412079, 0.41702221, 0.68130077]])

### create array containing 20 random integer then replace every even number with -1 
#### Example - 
####                  array --- >  [44,55,12,6,3] 
####                  ouput ----> [-1,55, -1,-1,3]


In [14]:
np.random.seed(123)
arr5 = np.random.randint(1,50,20)
arr5[arr5 %2 == 0] = -1
arr5

array([-1,  3, 29, 35, 39, -1, -1, 43, 23, -1, 33, -1, -1, 33, 47, 33, -1,
       -1, -1, 15])

#### You have a matrix 
[[5 , 10, 15, 20, 25],
[30, 35, 40, 45, 50],
[55, 60, 65, 70, 75],
[80, 85, 90, 95, 100]]

Extract
[30,35,40]
[55, 60, 65]

In [15]:
matrix = np.array([[5 , 10, 15, 20, 25],
                   [30, 35, 40, 45, 50],
                   [55, 60, 65, 70, 75],
                   [80, 85, 90, 95, 100]])
matrix[1:3,0:3 ]

array([[30, 35, 40],
       [55, 60, 65]])

### Concatenate two 1-d array   

In [16]:
arr7 = np.array([1,2,3])
arr8 = np.array([4,5,6])
np.hstack((arr7,arr8))

array([1, 2, 3, 4, 5, 6])

### Stack 2-d matrix horizontally and vertically

In [17]:
matrix2 = np.random.randint(1,10,9).reshape(3,3)
matrix3 = np.random.randint(10,20,9).reshape(3,3)

In [18]:
matrix2

array([[5, 1, 1],
       [5, 2, 8],
       [4, 3, 5]])

In [19]:
matrix3

array([[17, 12, 14],
       [18, 10, 17],
       [19, 13, 14]])

In [20]:
np.vstack((matrix2, matrix3))

array([[ 5,  1,  1],
       [ 5,  2,  8],
       [ 4,  3,  5],
       [17, 12, 14],
       [18, 10, 17],
       [19, 13, 14]])

In [21]:
np.hstack((matrix2, matrix3))

array([[ 5,  1,  1, 17, 12, 14],
       [ 5,  2,  8, 18, 10, 17],
       [ 4,  3,  5, 19, 13, 14]])