In [1]:
import numpy as np

In [2]:
arr = np.array([5,10,15,20,25,30])

In [3]:
sliced_array = arr[2:5].copy()

In [4]:
sliced_array

array([15, 20, 25])

In [5]:
sliced_array[:] = 0

In [6]:
sliced_array

array([0, 0, 0])

In [8]:
arr

array([ 5, 10, 15, 20, 25, 30])

In [ ]:
# if sliced_array = arr
# then any changes made to sliced_array will be on original array as they share comman location 